---
build_from:
  aarch64: arm64v8/alpine:3.18.4
  amd64: amd64/alpine:3.18.4
  armhf: arm32v6/alpine:3.18.4
  armv7: arm32v7/alpine:3.18.4
  i386: i386/alpine:3.18.4
codenotary:
  signer: codenotary@frenck.dev
