---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: hassio-addons/workflows/.github/workflows/labels.yaml@main
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
